build:
  version: "1.0"

cards:
  message: "Welcome to EazyBank cards related PROD APIs"
  contactDetails:
    name: "Reine Aishwarya - Product Owner"
    email: "aishwarya@eazybank.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345