build:
  version: "1.0"

loans:
  message: "Welcome to EazyBank loans related PROD APIs"
  contactDetails:
    name: "Reine Aishwarya - Product Owner"
    email: "aishwarya@eazybank.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345