server:
  port: 8071

spring:
  application:
    name: "configserver"
  profiles:
    active: git
  # active: native
  cloud:
    config:
      server:
        git:
          uri: https://github.com/adriangonzalez-code/eazyback-config.git
          default-label: master
          timeout: 5
          clone-on-start: true
          force-pull: true
          basedir: file:///D:/configserver
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"

encrypt:
  key: "SD68GFFB684J1UY8B4BOP41B86FTBH14D6F"

management:
  metrics:
    tags:
      application: ${spring.application.name}
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

logging:
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"